NiceAndEasyRecipes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("recipesite.urls"), name="recipesite-urls"),
    path('summernote/', include('django_summernote.urls')),
    path("accounts/", include("allauth.urls")),
]

recipesite/urls.py
from . import views
from django.urls import path
from .views import (RecipeList, RecipeDetail, RecipeLike, SubmissionDetail,
                    SubmissionListView, SubmissionLike, EditProfile,
                    EditSubmission, DeleteSubmission)

urlpatterns = [
    path('', views.RecipeList.as_view(), name='home'),
    path('submission_list', views.SubmissionListView.as_view(),
         name='submission_list'),
    path('submission_detail/<slug:slug>', views.SubmissionDetail.as_view(),
         name='submission_detail'),
    path('edit_submission/<int:submission_id>/', EditSubmission.as_view(),
         name='edit_submission'),
    path('delete_submission/<int:submission_id>/',
         views.DeleteSubmission.as_view(),
         name='delete_submission'),
    path('submit/', views.create_submission, name='submit'),
    path('edit_profile/', views.EditProfile.as_view(), name='edit_profile'),
    path('<slug:slug>/', views.RecipeDetail.as_view(), name='recipe_detail'),
    path('like/<slug:slug>', views.RecipeLike.as_view(), name='recipe_like'),
    path('submission_like/<slug:slug>', views.SubmissionLike.as_view(),
         name='submission_like'),
]

recipesite/models.py
from django.db import models
from django.contrib.contenttypes.fields import GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField
from django.db.models.signals import pre_save, post_save
from django.template.defaultfilters import slugify
from django.dispatch import receiver


STATUS = ((0, "Draft"), (1, "Published"))


class Comment(models.Model):
    title = models.CharField(max_length=200, default="no title")
    name = models.CharField(max_length=100, default="anon")
    email = models.EmailField()
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)
    submission = models.ForeignKey('Submission', related_name='comments',
                                   on_delete=models.CASCADE,
                                   null=True, blank=True)
    recipe = models.ForeignKey('Recipe', related_name='comments',
                               on_delete=models.CASCADE, null=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.pk:  # Only set the related title for new comments
            if self.submission:
                self.title = self.submission.title
            elif self.recipe:
                self.title = self.recipe.title
        super().save(*args, **kwargs)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return f"Comment {self.body} by {self.name}"


class Recipe(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="recipes")
    comment = models.ForeignKey(Comment, related_name='recipes',
                                on_delete=models.CASCADE,
                                null=True, blank=True)
    updated_on = models.DateTimeField(auto_now=True)
    description = models.TextField(default='description')
    ingredients = models.TextField(default='ingredients')
    instructions = models.TextField(default='instructions')
    featured_image = CloudinaryField('image', default='placeholder')
    excerpt = models.TextField(blank=True)
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    likes = models.ManyToManyField(
        User, related_name='recipe_likes', blank=True)

    class Meta:
        ordering = ["-created_on"]

    def __str__(self):
        return self.title

    def number_of_likes(self):
        return self.likes.count()


class Submission(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=120)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField()
    ingredients = models.TextField()
    instructions = models.TextField()
    comment = models.ForeignKey(Comment, related_name='submissions',
                                on_delete=models.CASCADE,
                                null=True, blank=True)
    featured_image = CloudinaryField('image', default='placeholder')
    username_id = models.ForeignKey(User, on_delete=models.CASCADE,
                                    default=1, related_name="submitter",
                                    unique=False)
    created_on = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(User, related_name='submission_likes',
                                   blank=True)
    status = models.IntegerField(choices=STATUS, default=0)

    class Meta:
        ordering = ["-created_on"]
        verbose_name_plural = 'Submissions'

    def __str__(self):
        return self.title

    def number_of_likes(self):
        return self.likes.count()

templates/edit_profile.html
{% extends "index.html" %}

{% block content %}

<div class="container edit">
  
  <div class="profile-info">
    <h3>Your Profile</h3>

      <p>Username: {{ username }}</p>

  </div>

  <div class="email-change">
    <h3>Email Address</h3>
    {% if message %}
      <p>{{ message }}</p>
    {% else %}  
      <p>Current Email: {{ email }}</p>
    {% endif %}  
    <form>

      <label for="email">New Email:</label><br>
      <input type="email" id="email" name="email" autocomplete="off"><br>
      <br>
      <input type="submit" value="Submit">

    </form>

  </div>

  <div class="submission-list">
    <h3>Your Recipes</h3>
      <p>Click on your recipe to read, edit or delete it</p>
      <ul>
        {% for submission in submissions %}
          <li><a href="{% url 'edit_submission' submission.id %}">{{ submission }}</a></li>
        {% endfor %}
      </ul>
  </div>
  
</div>
{%endblock%}

templates/edit_submission.html
{% extends "index.html" %}

{% block content %}

{% load crispy_forms_tags %}

<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Save changes">
    <a href="{% url 'delete_submission' submission.id %}">Delete submission</a>
</form>

{% endblock %}

templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="A website to find simple, easy recipes and share your favourites">
    <meta name="keywords" content="simple recipe, easy recipe, easy, simple, cooking, home, tasty">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Libre+Baskerville&family=Montserrat&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/e576ca19f3.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Nice And Easy Recipes</title>
</head>

<body class="container-fluid">

  <header>
      
    <a href="{% url 'home' %}"><h1>Nice and Easy Recipes</h1></a>
        

    <div class="list-group list-group-horizontal-sm me-0" id="menu">

      <a href="{% url 'home' %}" class="list-group-item list-group-item-action px-3 border-0">Home</a>
      <a href="{% url 'submission_list' %}" class="list-group-item list-group-item-action px-3 border-0">Member's Recipes</a>
      {% if user.is_authenticated %}
      <a href="{% url 'submit' %}" class="list-group-item list-group-item-action px-3 border-0">Submit a Recipe</a>
      <a href="{% url 'edit_profile' %}" class="list-group-item list-group-item-action px-3 border-0">Edit Profile</a>
      <a href="{% url 'account_logout' %}" class="list-group-item list-group-item-action px-3 border-0">Log Out</a>
      {% else %}
      <a href="{% url 'account_login' %}" class="list-group-item list-group-item-action px-3 border-0">Log In</a>
      <a href="{% url 'account_signup' %}" class="list-group-item list-group-item-action px-3 border-0">Sign Up</a>
      {% endif %}
    </div> 
    
    {% include 'messages.html' %}
            
  </header>
  
  <main>

        {% block content %}

        {% endblock content %}
  </main>



  <footer>
        
    <div class="footer-content">
         
      <a href="{% url 'home' %}"><h3 class="text-center">Nice and Easy Recipes</h3></a>

      <p class="text-center">
          Follow us on social-media
      </p>
    

        <div class="mb-4 text-center">
            <a class="btn btn-floating m-1" href="https://facebook.com" role="button" target="_blank" rel="noopener"
                aria-label="Visit our Facebook page (opens in a new tab)"><i class="fab fa-facebook-square"></i></a>

            <a class="btn btn-floating m-1" href="https://twitter.com" role="button" target="_blank" rel="noopener"
                aria-label="Visit our Twitter page (opens in a new tab)"><i class="fab fa-twitter-square"></i></a>

            <a class="btn btn-floating m-1" href="https://youtube.com" role="button" target="_blank" rel="noopener"
                aria-label="Visit our YouTube page (opens in a new tab)"><i class="fab fa-youtube-square"></i></a>

            <a class="btn btn-floating m-1" href="https://instagram.com" role="button" target="_blank" rel="noopener"
                aria-label="Visit our Instagram page (opens in a new tab)"><i class="fab fa-instagram"></i></a>



        </div>

        <div class="footer-bottom">
          <p>© Michelle Brady 2023</p>
        </div>

    </div>
      
  </footer>

</body>
</html>

templates/member_recipes_page.html
{% extends "index.html" %}

{% block content %}

<div class="container-fluid justify-content-center p-0 me-2 ms-2">
    <div class="row justify-content-around vh100"> 
        <!--alert message-->
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        <!--recipe entry-->
        {% for members_recipes in members_recipes_list %}
        <div class="card-group col-sm-4">
                <div class="card" style="background-color:#bebcbc;">
                                {% if "placeholder" in members_recipes.featured_image.url %}
                                <img class="card-img-top"
                                    src="https://res.cloudinary.com/dhifyjuus/image/upload/v1677244923/enrdln0vg7f2igyturbd.jpg">
                                <a href="#!">
                                    <div class="mask" style="background-color: rgba(251, 251, 251, 0.15)"></div>
                                </a>    
                                {% else %}  
                                <img class="card-img-top" src="{{ members_recipes.featured_image.url }}">
                                <a href="#!">
                                    <div class="mask" style="background-color: rgba(251, 251, 251, 0.15)"></div>
                                </a>
                                {% endif %}

                            <a href="{% url members_recipes.slug  %}">
                                <h3 class="card-header">{{ members_recipes.title }}</h3>
                                <h4 class="author">{{ members_recipes.author }}</h4>
                            </a>

                            <div class="card-footer pb-3" style="background-color: lightgray;">{{ members_recipes.created_on}} <i class="far fa-heart"></i>
                                 {{ members_recipes.number_of_likes }}</div>
                        </div>       
                </div>    
                {% if forloop.counter|divisibleby:2 %}

            <div class="row justify-content-around">
               {% endif %}
               {% endfor %}
            </div>
        </div>
</div>        
    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center ">
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link" style="color: black; font-weight: 500; font-size: 1em;">&laquo; PREV </a></li>
            {% endif %}
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="page-link" style="color: black; font-weight: 500; font-size: 1em;"> NEXT &raquo;</a></li>

           {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>
{%endblock%}

templates/members_recipes_detail.html
{% extends 'index.html' %} {% block content %}
{% load crispy_forms_tags %}

<div class="masthead">
    <div class="container">
        <div class="row g-0">
            <div class="col-md-6 masthead-text">
                <!-- Post title goes in these h1 tags -->
                <h1 class="recipe-title">{{ members_recipes.title }}</h1>
                <!-- Post author goes before the | the post's created date goes after -->
                <p class="recipe-subtitle">{{ members_recipes.author }} | {{ members_recipes.created_on }}</p>
            </div>
            <div class="d-none d-md-block col-md-6 masthead-image">
                <!-- The featured image URL goes in the src attribute -->
                {% if "placeholder" in members_recipes.featured_image.url %}
                <img src="https://res.cloudinary.com/dhifyjuus/image/upload/v1676972420/pp4recipes/woman-6760877_1280_bdxsqo.jpg" width="100%">
                {% else %}
                <img src=" {{ members_recipes.featured_image.url }}" width="100%">
                {% endif %}
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col card mb-4 mt-3 left top">
            <div class="card-body" style="border: 1px solid darkgreen">
                <div class="ingredients-title">
                    <h3 >Ingredients</h3>
                </div>
                <div class="recipe-ingredients col card mb-4 mt-3">
                    <p>{{ members_recipes.ingredients | safe }}</p>
                </div>
            </div>
        </div>
    </div>     

    

    <div class="row">
        <div class="col card mb-4  mt-3 left  top ">
            <div class="card-body" style="border: 1px solid darkgreen">
                <div class="instructions-title">
                    <h3>Instructions</h3>
                </div>
                <div class="recipe-instructions col card mb-2 mt-2">
                    <p>{{ members_recipes.instructions | safe }}</p>
                </div>
            </div>
        </div>
    </div>

    <hr /> 
                
                <div class="row">
                    <div class="col-2">
                        <strong>
                            {% if user.is_authenticated %}
                            <form class="d-inline" action="{% url 'recipe_like' recipe.slug %}" 
                                method="POST">
                                {% csrf_token %}
                                {% if liked %}

                                <button type="submit" name="recipe_id" value="{{membersrecipeslug}}" class="btn-like">
                                    <i class="fas fa-heart"></i> 
                                </button>

                                {% else %}

                                <button type="submit" name="recipe_id" value="{{membersrecipes.slug}}" class="btn-like">
                                    <i class="far fa-heart"></i>
                                </button>

                                {% endif %}

                            </form>

                            {% else %}

                            <span class="text-secondary"><i class="far fa-heart"></i></span>
                            {% endif %}
                            <!-- The number of likes goes before the closing strong tag -->
                            <span class="text-secondary">{{ recipe.number_of_likes }} </span>
                        </strong>
                    </div>

                    <div class="col-1">
                        {% with comments.count as total_comments %}   
                        <strong class="text-secondary"><i class="far fa-comments"></i>
                            <!--total_comments variable-->
                            {{ total_comments }}
                        </strong>
                        {% endwith %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <hr>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 card mb-4  mt-3 ">
            <h3>Comments:</h3>
            <div class="card-body">
                <!-- for loop inside the tags to iterate through each comment in comments -->
                {% for comment in comments %}
                <div class="comments" style="padding: 10px;">
                    <p class="font-weight-bold">
                        <!-- The commenter's name goes here. Check the model if you're not sure what that is -->
                        {{ comment.name }}
                        <span class=" text-muted font-weight-normal">
                            <!-- The comment's created date goes here -->
                            {{ comment.created_on }}
                        </span> wrote:
                    </p>
                    <!-- The body of the comment goes before the | -->
                    {{ comment.body | linebreaks }}
                </div>
                <!-- Our for loop ends here -->
                {% endfor %}
            </div>
        </div>
        <div class="col-md-4 card mb-4  mt-3 ">
            <div class="card-body">
                <!-- connect to crispy comment form --> 
                {% if commented %}          
                <div class="alert alert-success" role="alert">
                    Your comment is awaiting approval
                </div>
                {% else %}
                {% if user.is_authenticated %}

                <h3>Leave a comment on this recipe:</h3>
                <p>Posting as: {{ user.username }}</p>
                <form method="post" style="margin-top: 1.3em;">
                    {{ comment_form|crispy }}
                    {% csrf_token %}
                    <button type="submit" class="btn btn-signup btn-lg">Submit Comment</button>
                </form>
                {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/messages.html
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

templates/post_detail.html
{% extends 'index.html' %} {% block content %}
{% load crispy_forms_tags %}

<div class="masthead">
    <div class="container">
        <div class="row g-0">
            <div class="col-md-6 masthead-text">
                <!-- Post title goes in these h1 tags -->
                <h1 class="post-title">{{ post.title }}</h1>
                <!-- Post author goes before the | the post's created date goes after -->
                <p class="post-subtitle">{{ post.author }} | {{ post.created_on }}</p>
            </div>
            <div class="d-none d-md-block col-md-6 masthead-image">
                <!-- The featured image URL goes in the src attribute -->
                {% if "placeholder" in post.featured_image.url %}
                <img src="https://res.cloudinary.com/dhifyjuus/image/upload/v1676972420/pp4recipes/woman-6760877_1280_bdxsqo.jpg" width="100%">
                {% else %}
                <img src=" {{ post.featured_image.url }}" width="100%">
                {% endif %}
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col card mb-4 mt-3 left top">
            <div class="card-body" style="border: 1px solid darkgreen">
                <div class="ingredients-title">
                    <h3 >Ingredients</h3>
                </div>
                <div class="post-ingredients col card mb-4 mt-3">
                    <p>{{ post.ingredients | safe }}</p>
                </div>
            </div>
        </div>
    </div>     

    

    <div class="row">
        <div class="col card mb-4  mt-3 left  top ">
            <div class="card-body" style="border: 1px solid darkgreen">
                <div class="instructions-title">
                    <h3>Instructions</h3>
                </div>
                <div class="post-instructions col card mb-2 mt-2">
                    <p>{{ post.instructions | safe }}</p>
                </div>
            </div>
        </div>
    </div>

    <hr /> 
                
                <div class="row">
                    <div class="col-2">
                        <strong>
                            {% if user.is_authenticated %}
                            <form class="d-inline" action="{% url 'post_like' post.slug %}" 
                                method="POST">
                                {% csrf_token %}
                                {% if liked %}

                                <button type="submit" name="recipepost_id" value="{{post.slug}}" class="btn-like">
                                    <i class="fas fa-heart"></i> 
                                </button>

                                {% else %}

                                <button type="submit" name="recipepost_id" value="{{post.slug}}" class="btn-like">
                                    <i class="far fa-heart"></i>
                                </button>

                                {% endif %}

                            </form>

                            {% else %}

                            <span class="text-secondary"><i class="far fa-heart"></i></span>
                            {% endif %}
                            <!-- The number of likes goes before the closing strong tag -->
                            <span class="text-secondary">{{ post.number_of_likes }} </span>
                        </strong>
                    </div>

                    <div class="col-1">
                        {% with comments.count as total_comments %}   
                        <strong class="text-secondary"><i class="far fa-comments"></i>
                            <!--total_comments variable-->
                            {{ total_comments }}
                        </strong>
                        {% endwith %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <hr>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 card mb-4  mt-3 ">
            <h3>Comments:</h3>
            <div class="card-body">
                <!-- for loop inside the tags to iterate through each comment in comments -->
                {% for comment in comments %}
                <div class="comments" style="padding: 10px;">
                    <p class="font-weight-bold">
                        <!-- The commenter's name goes here. Check the model if you're not sure what that is -->
                        {{ comment.name }}
                        <span class=" text-muted font-weight-normal">
                            <!-- The comment's created date goes here -->
                            {{ comment.created_on }}
                        </span> wrote:
                    </p>
                    <!-- The body of the comment goes before the | -->
                    {{ comment.body | linebreaks }}
                </div>
                <!-- Our for loop ends here -->
                {% endfor %}
            </div>
        </div>
        <div class="col-md-4 card mb-4  mt-3 ">
            <div class="card-body">
                <!-- connect to crispy comment form --> 
                {% if commented %}          
                <div class="alert alert-success" role="alert">
                    Your comment is awaiting approval
                </div>
                {% else %}
                {% if user.is_authenticated %}

                <h3>Leave a comment on this recipe:</h3>
                <p>Posting as: {{ user.username }}</p>
                <form method="post" style="margin-top: 1.3em;">
                    {{ comment_form|crispy }}
                    {% csrf_token %}
                    <button type="submit" class="btn btn-signup btn-lg">Submit Comment</button>
                </form>
                {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/recipes.html
{% extends "index.html" %}

{% block content %}
<div class="container justify-content-center">
    <div class="row">
        <div class="col-md-12 mt-3 md-2">
            <h3 class="welcome" style="font-weight: 600;">Welcome</h3>
                <div class="about">
                    <h4 class="intro">
                     Welcome to our community of food lovers! Our website is a place where members can share their favorite recipes and discover new ones. Whether you're an experienced cook or just starting out, we invite you to join us and share your culinary creations. Let's cook, share, and enjoy delicious meals together!
                    </h4>
                </div>  
        </div>
    </div>
</div>
<div class="container-fluid justify-content-center p-0 me-2 ms-2">
    <div class="row justify-content-center vh100"> 
        
        {% for recipe in recipe_list %}
        <div class="card-group col-sm-4">
                <div class="card" style="background-color:lightgray;">
                                {% if "placeholder" in recipe.featured_image.url %}
                                <img class="card-img-top"
                                    src="https://res.cloudinary.com/dhifyjuus/image/upload/v1692001880/pp4recipes/recipe_ingredients_dftsnu.webp" alt="photo of ingredients">
                                <a href="#!">
                                    <div class="mask" style="background-color: rgba(251, 251, 251, 0.15)"></div>
                                </a>    
                                {% else %}  
                                <img class="card-img-top" src="{{ recipe.featured_image.url }}" alt="photo of delicious food">
                                <a href="#!">
                                    <div class="mask" style="background-color: rgba(251, 251, 251, 0.15)"></div>
                                </a>
                                {% endif %}

                            <a href="{% url 'recipe_detail' recipe.slug  %}">
                                <h3 class="card-header">{{ recipe.title }}</h3>
                                <h4 class="author">{{ recipe.author }}</h4>
                            </a>

                            <div class="card-footer" style="background-color: lightgray;">{{ recipe.created_on}} <i class="far fa-heart"></i>
                                 {{ recipe.number_of_likes }}</div>
                        </div>       
                </div>    
                {% if forloop.counter|divisibleby:2 %}

            <div class="row justify-content-center">
               {% endif %}
               {% endfor %}
            </div>
        </div>
    </div>    
</div>        
    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center ">
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link" style="color: black; font-weight: 500; font-size: 1em;">&laquo; PREV </a></li>
            {% endif %}
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="page-link" style="color: black; font-weight: 500; font-size: 1em;"> NEXT &raquo;</a></li>

           {% endif %}
        </ul>
    </nav>
    {% endif %}

{%endblock%}

templates/submission.html
{% extends "index.html" %} 
{%load crispy_forms_tags %}


{% block content %}

<h1>Submit a Recipe of Your Own</h1>

  <form method="post" action="{% url 'submit' %}">
    {% csrf_token %}
    {% crispy form %}
  </form>


{% endblock %}

templates/submit_recipe.html
{% extends "index.html" %} 
{%load crispy_forms_tags %}


{% block content %}

<h1>Submit a Recipe of Your Own</h1>

<form method="post" action="{% url 'submit' %}">
  {% csrf_token %}
  {% crispy form %}
</form>

{% endblock %}